services:
  postgresqldb:
    image: postgres:17
    container_name: ticketmaster-postgres
    environment:
      POSTGRES_USER: ticketmaster
      POSTGRES_PASSWORD: ticketmaster
      POSTGRES_DB: ticketmasterdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: